<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE routes [
<!ELEMENT route (url, method, controller, action, format)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT method (#PCDATA)>
<!ELEMENT controller (#PCDATA)>
<!ELEMENT action (#PCDATA)>
<!ELEMENT format (#PCDATA)>  
]>
<!--
    Route file.
    In this XML file there are specified all the applications routes.
    There is also specified a small DTD requirements to ensure the
    correctness of the file. 
    Author: Giovanni De Toni
-->
<routes>
    <route>
        <url>/</url>
        <method>GET</method>
        <controller>StaticPages</controller>
        <action>home</action>
        <format>html</format>            
    </route>
    <route>
        <url>/protected</url>
        <method>GET</method>
        <controller>StaticPages</controller>
        <action>protected_pages</action>
        <format>html</format>            
    </route>
</routes>
